"""Add paid_amount to bookings

Revision ID: 46298bff4be0
Revises: 0452c0ac8374
Create Date: 2026-07-29 20:20:16.060333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46298bff4be0'
down_revision = '0452c0ac8374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')

    # ### end Alembic commands ###
