"""Add vehicle_id to bookings

Revision ID: f8b8cf1b2055
Revises: 24b22c3b5d53
Create Date: 2026-07-30 13:59:29.486648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b8cf1b2055'
down_revision = '24b22c3b5d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_bookings_vehicle_id', 'vehicles', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bookings_vehicle_id', type_='foreignkey')
        batch_op.drop_column('vehicle_id')

    # ### end Alembic commands ###
